version: ~> 1.0
notifications:
  email: false
import:
  - source: 'form8ion/.travis-ci:node.yml'
  - source: 'form8ion/.travis-ci:authenticated-semantic-release.yml'
script:
  - "c=0; while true; do npm run lint:travis && ((c = c + 1)) || break; sleep 1; echo $c; done"
after_success: 'npm run coverage:report'
